# Generated by Django 5.1.1 on 2024-09-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_num',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(default='', max_length=80),
        ),
    ]
